# Generated by Django 3.2.7 on 2021-09-06 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='manner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('like', models.IntegerField()),
                ('dis_like', models.IntegerField()),
                ('hashtag_me', models.CharField(max_length=20)),
                ('hashtag_you', models.CharField(max_length=20)),
                ('hashtag_situation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('non_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='communityText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('like', models.IntegerField()),
                ('dis_like', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='communityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('dis_like', models.IntegerField()),
                ('text', models.CharField(max_length=300)),
                ('communitytext', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.communitytext')),
            ],
        ),
    ]
