# Generated by Django 3.2.6 on 2021-11-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211111_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='manner',
            name='secret',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
