# Generated by Django 3.2.6 on 2021-11-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211110_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manner',
            name='modify_date',
        ),
    ]
