# Generated by Django 3.2.7 on 2021-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210930_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manner',
            name='hashtag_situation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='manner',
            name='text',
            field=models.CharField(max_length=18),
        ),
    ]
