# Generated by Django 3.2.6 on 2021-11-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_manner_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytext',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
