# Generated by Django 3.2.7 on 2021-10-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211030_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='newterm',
            name='randanswer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newterm',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newterm',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
