# Generated by Django 3.2.6 on 2021-11-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_communitytext_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='getcoin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='communitytext',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
