# Generated by Django 3.2.6 on 2021-11-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='getcoin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
