# Generated by Django 3.2.7 on 2021-10-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211030_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newterm',
            name='score',
            field=models.IntegerField(default=-2),
        ),
    ]
