# Generated by Django 3.2.6 on 2021-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211111_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='manner',
            name='getcoin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
