# Generated by Django 3.2.7 on 2021-11-01 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_newterm_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newterm',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('productName', models.CharField(default='', max_length=30)),
                ('productText', models.CharField(default='', max_length=500)),
                ('like', models.IntegerField()),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
