# Generated by Django 3.2.7 on 2021-11-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211101_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productText',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
