# Generated by Django 3.2.7 on 2021-11-09 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manner',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
