# Generated by Django 3.2.6 on 2021-11-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('', '나이대를 선택하세요'), ('5', '10대 이하'), ('10', '10대'), ('20', '20대'), ('30', '30대'), ('40', '40대'), ('50', '50대 이상')], help_text='나이대를 선택하세요', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('', '성별을 선택하세요'), ('남', '남'), ('여', '여')], help_text='성별을 선택하세요', max_length=3),
        ),
    ]
