# Generated by Django 3.2.7 on 2021-10-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210923_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.CharField(choices=[('5', '10대 이하'), ('10', '10대'), ('20', '20대'), ('30', '30대'), ('40', '40대'), ('50', '50대 이상')], help_text='나이대를 선택하세요', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('M', '남'), ('W', '여')], help_text='성별을 선택하세요', max_length=3),
        ),
    ]
