# Generated by Django 3.2.7 on 2021-11-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211101_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('', '성별을 선택하세요'), ('남', '남'), ('여', '여')], help_text='성별을 선택하세요', max_length=3),
        ),
    ]
